Repository Uspacy/uspacy-go-sdk, pull requests merged in 2023-04, with the labels that each got.

#15 Add feature for working with users
  api/api.go
  api/user.go
  common/types.go
  crm/types.go
  user/types.go
Labels: size/l, size/m

#16 Fix field struct type
  crm/types.go
Labels: size/m

#17 Fix users and crm
  api/user.go
  crm/types.go
  user/types.go
Labels: size/m, size/s, size/xs

#18 fix response struct for created users
  api/user.go
  user/types.go
Labels: size/l, size/xs

#22 temporary crm fix
  crm/types.go
Labels: size/s

#24 Hotfix/temporary crm fix (KanbanStageId interface{})
  crm/types.go
Labels: size/s

#25 Add CreateTask & PatchObject in CRM
  api/crm.go
  api/user.go
  crm/types.go
Labels: size/l, size/m

#27 Hotfiх/add posts in newsfeed
  api/newsfeeds.go
  newsfeed/types.go
Labels: size/s

#26 Feature/add departments
  api/departments.go
  departments/types.go
Labels: size/m

#28 Hotfix/refresh token fix
  api/api.go
  api/auth.go
  auth/types.go
Labels: size/l, size/m, size/xs

#30 PatchEntity CRM fix
  api/crm.go
Labels: size/xs

#32 Entity place fix
  crm/types.go
Labels: size/xs

#33 Add Create Task
  api/crm.go
  api/tasks.go
  task/types.go
Labels: size/m

#35 Hotfix/departments create fix
  api/departments.go
Labels: size/s, size/xs

#36 Update auth.go
  api/auth.go
Labels: size/xs

#41 fix doPostFormData
  api/api.go
Labels: size/s

#37 Add retries to doRaw
  api/api.go
Labels: size/s

#42 fix doPostFormData
  api/api.go
Labels: size/s

#43 fix post newsfeed
  api/newsfeeds.go
  api/tasks.go
  newsfeed/types.go
Labels: size/m

#44 fix post
  api/newsfeeds.go
Labels: size/xs

#45 Fix logg
  api/api.go
Labels: size/xs

#50 FunnelStage updates
  api/crm.go
  crm/types.go
Labels: size/m

#49 refreshToken fix
  api/api.go
  api/auth.go
Labels: size/m

#53 GetAllFunnelStages
  api/crm.go
Labels: size/s

#55 Add GetFunnels
  api/crm.go
  crm/types.go
Labels: size/s

#56 refresh token fix
  api/api.go
  go.mod
  go.sum
Labels: size/m, size/s
