Repository Uspacy/uspacy-go-sdk, pull requests merged in 2023-05, with the labels that each got.

#58 Delete CRM field by code
  api/api.go
  api/crm.go
Labels: size/s

#59 refresh fix url for create field
  api/api.go
  api/crm.go
  crm/types.go
Labels: size/xs

#60 add CreateFiles method
  api/api.go
  api/files.go
  api/groups.go
  api/newsfeeds.go
  api/tasks.go
  files/types.go
Labels: size/m

#61 fix: minor changes
  api/api.go
  api/files.go
  files/types.go
Labels: size/xs

#62 public refresh token
  api/api.go
  api/auth.go
Labels: size/s

#63 remove log.Fatal
  api/auth.go
Labels: size/xs

#65 Increase defaultClientTimeout from 10 to 20 sec
  api/api.go
  crm/types.go
Labels: size/xs

#66 CreateTaskCRM
  api/crm.go
  crm/types.go
Labels: size/s

#67 hotfix
  api/crm.go
Labels: size/xs
