Repository Uspacy/uspacy-go-sdk, pull requests merged in 2023-03, with the labels that each got.

#9 [CU-865bvzxyw] Create entity fields, lists, funnels, funnel stages and move funnel stages
  api/crm.go
  api/fields.go
  crm/types.go
  go.mod
  go.sum
Labels: size/l

#10 Main host fix
  api/api.go
  api/auth.go
  api/crm.go
  api/groups.go
  api/newsfeeds.go
  api/tasks.go
  api/uri.go
  crm/types.go
Labels: size/m

#12 CreateObjectMethod implementation
  api/crm.go
Labels: size/s

#13 Add header content-type
  api/api.go
Labels: size/xs
