Repository Uspacy/uspacy-go-sdk, pull requests merged in 2024-03, with the labels that each got.

#94 add function of deleting files from fileservice
  api/files.go
Labels: size/s

#93 add SmartObjects for crm
  crm/types.go
Labels: size/xs

#98 Create codeql.yml
  .github/workflows/codeql.yml
Labels: size/m
